### ISSUE TITLE
Expose API access to cookie creation

### ISSUE THREAD

**Issue by Raynos** [npm/redsess#3]
https://github.com/jed/cookies#cookiesset-name--value---options--

You can set things like path and domain.

I need to be able to say "all session cookies need this custom domain string"

**Comment by isaacs** [comment]
+1.  patch welcome.

**Comment by robertjd** [comment]
Here are two ideas for solving this problem:

Patching redsess: https://github.com/Colingo/redsess/commit/1b189f3af921a0845c50c6d0dbd13f08905174de

Patching cookies: https://github.com/Colingo/cookies/commit/b2cc603f23dd2b5d07ce3cc783b4d5116d3c30f2

**Comment by isaacs** [comment]
@robertjd Send pull requests.

**Comment by lxe** [comment]
Looks like this has been solved by @robertjd's https://github.com/npm/redsess/commit/e5185944ed2e650d9abcc6fa700ba84819fd6b13
